### ISSUE TITLE
Are there any problems using XCode 4 with Workspaces?

### ISSUE THREAD

**Issue by aglemann** [lukeredpath/betabuilder#13]
BetaBuilder goes along fine until it gets to adding libraries from other projects in our Workspace:

ld: library not found for -lRestKitJSONParserYAJL
collect2: ld returned 1 exit status
Command /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 failed with exit code 1

I've set the HEADER_SEARCH_PATHS and running/archiving from within XCode works fine. Is there something I'm missing or another configuration I can make?

Thank you!

**Comment by lukeredpath** [comment]
I've not tested betabuilder extensively with Xcode 4, however it relies entirely on xcodebuild to build the project.

Are you able to build your project on the command line manually using the xcodebuild tool?

**Comment by aglemann** [comment]
Hey, tks for the xcodebuild lead! So, yes I am able to do a build using the alternate syntax in xcode 4 for workspaces:

xcodebuild -workspace <workspacename> -scheme <schemeName> [-configuration <configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]] [<buildsetting>=<value>]... [<buildaction>]...

I found a couple of articles that were helpful:

http://blog.carbonfive.com/2011/04/06/building-xcode-4-projects-from-the-command-line/
http://blog.carbonfive.com/2011/05/04/automated-ad-hoc-builds-using-xcode-4/

**Comment by aglemann** [comment]
So I had to make 1 small change to get this to work with betabuilder. If "workspace" is set in config it will use the alternate build arguments... it would be nice if betabuilder could find the DerivedData folder the workspace is using, but at the moment I can set it by hand with the build_dir arg. Sending a pull request separately... Thanks Luke!

**Comment by lukeredpath** [comment]
Just to update this ticket, betabuilder now fully supports Xcode 4. Please try the new release in case of any niggles.
