### ISSUE TITLE
Cleaning & Compiling of Subprojects

### ISSUE THREAD

**Issue by mattvv** [lukeredpath/betabuilder#18]
I have dependent subprojects which are written in C++.
These build fine in debug mode and clean correctly, however using betabuilder the build does not clean and I do not get a recompiled version of the subproject. Is there any simple way to turn this on?

Thanks

**Comment by lukeredpath** [comment]
Betabuilder is running 'xcodebuild clean' but I suspect there might be a cleanall command. 

Could you experiment with xcodebuild (it has a manpage) in your project and see what works?

**Comment by mattvv** [comment]
Will do :) I'll update this ticket with my findings

**Comment by mattvv** [comment]
From my findings I got the following results.

`xcodebuild -workspace x.xcworkspace -scheme x clean -configuration Ad-hoc`
would clean the subprojects while

`xcodebuild clean` would not clean the subprojects only the main project.

I have absolutely defined the workspace and scheme in my rakefile, any ideas why these arguments wouldn't be parsed to xcodebuild?

**Comment by lukeredpath** [comment]
Hmm, looking at the code it seems that the same build arguments for building are passed on to the clean command. Just to confirm, you've set the `workspace_path` and `scheme` configuration properties?

If you run `rake beta:clean` you should see the xcodebuild output in the terminal. What is being run?

**Comment by mattvv** [comment]
rake beta:clean
(in /Users/matt/Documents/curiousminds/xx)
`=== CLEAN NATIVE TARGET xx OF PROJECT xx WITH THE DEFAULT CONFIGURATION (Ad-hoc) ===`

instead of cleaning correctly.

I have both
  config.workspace_path = "x.xcworkspace"
  config.scheme         = "x"
Set in my rakefile, along with configuration

**Comment by mattvv** [comment]
Wow looks like i'm the silly one here.
bundle update worked on this. I must have been using a very old version!
Apologies for wasted time on this luke :(
