### ISSUE TITLE
Deploy with testflight fails if no distribution_lists is provided

### ISSUE THREAD

**Issue by hongrich** [lukeredpath/betabuilder#2]
betabuilder should probably default to no distribution_lists if none is provided in the Rakefile. I got this message when running deploy using testflight but with no distribution_lists set. 
    rake aborted!
    undefined method `join' for nil:NilClass

**Comment by lukeredpath** [comment]
Stupid mistake on my part!

**Comment by lukeredpath** [comment]
Default to an empty distribution list (closed by b1f70398461d462d4f8dba64ec3fe7f095caf160)

**Comment by lukeredpath** [comment]
Pushed a 0.3.2 gem release.
