### ISSUE TITLE
Build & Archive default directory correct?

### ISSUE THREAD

**Issue by sujal** [lukeredpath/betabuilder#7]
On my system, xcode's build & archive function puts files in 

```
~/Library/Application\ Support/Developer/Shared/Archived\ Applications
```

What version of XCode are you running? I'm on 3.2.5 1760

**Comment by lukeredpath** [comment]
Updated the default archived build path to match the newer Xcode archived build location. (Closed by 5143b9564fa04356f6b24ebbd6db583daf81bb31).
