### ISSUE TITLE
Issue when product name is not the same as the target name

### ISSUE THREAD

**Issue by mwhuss** [lukeredpath/betabuilder#8]
I use different product names for each of my different deployments (dev, adhoc, app store). When I attempted to use BetaBuilder to upload to testflightapp it built my Ad Hoc version of the app but then assumed the .app was the same name as the target. This resulted in uploading an old version of my app to testflight and not the one I intended.

**Comment by lukeredpath** [comment]
Hi there, could you give me a bit more information. It would be helpful to see:
- Your configured Rake task (feel free to redact the app name)
- What happened
- What was supposed to happen

With this, I'm sure I'll be able to commit a fix.

**Comment by mwhuss** [comment]
I'll either do that or fix and send a pull request when I can find some time, thanks.

**Comment by mwhuss** [comment]
I believe this commit may have fixed my issue.

https://github.com/lukeredpath/betabuilder/commit/80b2d88b14137dbcd0d7cfaf222b45dec12353c9

Closing issue until I encounter it again.
